# Specifies which syntax version of Docker compose
version: '4'

# Build a multiservice arhitecture.
services:
  # Create a service called web
  ui:
    # Build an image from the files in the project root directory (Dockerfile)
    build: ./countries_and_states
    # Assigns a name for the container. If no name is specified,
    # Docker will assign the container a random name
    container_name: countrystate_ui
    # Mount the container `/drf` folder to the a `src` folder in the location
    # of the Dockerfile on the host machine.
    volumes:
      - ./countries_and_states:/app
    # Map port 8000 to port 9090 so that we can access the application on
    # our host machine by visiting 127.0.0.1:9090
    ports:
      - "3000:3000"
  api:
    build: ./csbackend/csmysite
    # Assigns a name for the container. If no name is specified,
    # Docker will assign the container a random name
    container_name: countrystate_api
    # Mount the container `/drf` folder to the a `src` folder in the location
    # of the Dockerfile on the host machine.
    volumes:
      - ./csbackend/csmysite:/app
    # Map port 8000 to port 9090 so that we can access the application on
    # our host machine by visiting 127.0.0.1:9090
    ports:
      - "8000:8000"